-- 创建绩效评审表
CREATE TABLE IF NOT EXISTS performance_reviews (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    review_no VARCHAR(50) UNIQUE,
    agent_id VARCHAR(50) NOT NULL,
    agent_name VARCHAR(100),
    agent_role VARCHAR(50),
    producer_id VARCHAR(50) NOT NULL,
    producer_name VARCHAR(100),
    project_id VARCHAR(100),
    project_name VARCHAR(200),
    review_period VARCHAR(20) NOT NULL,
    quality_score INT,
    efficiency_score INT,
    collaboration_score INT,
    innovation_score INT,
    overall_score INT,
    strengths TEXT,
    improvements TEXT,
    comments TEXT,
    highlights TEXT,
    status VARCHAR(20) DEFAULT 'COMPLETED',
    is_warning BOOLEAN DEFAULT FALSE,
    warning_reason TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_review_agent (agent_id),
    INDEX idx_review_producer (producer_id),
    INDEX idx_review_project (project_id),
    INDEX idx_review_period (review_period),
    INDEX idx_review_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建解雇申请表
CREATE TABLE IF NOT EXISTS dismissal_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    request_no VARCHAR(50) UNIQUE,
    agent_id VARCHAR(50) NOT NULL,
    agent_name VARCHAR(100),
    agent_role VARCHAR(50),
    is_system_role BOOLEAN DEFAULT FALSE,
    producer_id VARCHAR(50) NOT NULL,
    producer_name VARCHAR(100),
    project_id VARCHAR(100),
    project_name VARCHAR(200),
    reason_type VARCHAR(50),
    reason TEXT,
    warning_count INT DEFAULT 0,
    last_warning_at DATETIME,
    last_warning_reason TEXT,
    performance_history TEXT,
    consecutive_low_score_periods INT DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    approver_id BIGINT,
    approver_name VARCHAR(50),
    approved_at DATETIME,
    approval_comment TEXT,
    rejection_reason TEXT,
    executed_at DATETIME,
    executed_by VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_dismissal_agent (agent_id),
    INDEX idx_dismissal_producer (producer_id),
    INDEX idx_dismissal_status (status),
    INDEX idx_dismissal_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 创建制作人更换记录表
CREATE TABLE IF NOT EXISTS producer_replacements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    replacement_no VARCHAR(50) UNIQUE,
    project_id VARCHAR(100) NOT NULL,
    project_name VARCHAR(200),
    old_producer_id VARCHAR(50) NOT NULL,
    old_producer_name VARCHAR(100),
    new_producer_id VARCHAR(50) NOT NULL,
    new_producer_name VARCHAR(100),
    reason_type VARCHAR(50),
    reason TEXT,
    new_guidelines TEXT,
    admin_id BIGINT,
    admin_name VARCHAR(50),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_replacement_project (project_id),
    INDEX idx_replacement_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
